server:
  port: 7071
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jorgecahui/config-repo.git
          searchPaths: config-data
          default-label: main
          username: ${GIT_USERNAME:jorgecahui}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: 123456